"""
ActProof Chess Sensor — measurement instrument, not a chess engine.

Computes field metrics for a chess position:
  Z(x,y) — continuous information potential (Coulomb-like, 1/r decay, signed by color)
  T(x,y) — latent tension field = ‖∇Z‖ (informational stress)
  E      — Dirichlet energy ∫ ‖∇Z‖² dx dy (total positional tension, a scalar)
  S      — Shannon entropy of stochastic policy over legal moves (bits)

Stochastic policy:
  For each legal move j we compute E_j = Dirichlet energy of the position
  resulting from playing j. We then define
                p_j ∝ exp(-β · E_j)
  This is a Boltzmann *sampling distribution*, NOT a model of how a human
  chooses moves. It answers: "if a tension-minimising sampler were drawing
  from the legal-move distribution, how concentrated would the draw be?" —
  and S quantifies that concentration.

Validation idiom (analogous to your KataGo work on Go):
  feed grandmaster PGNs, locate the played move in the policy distribution,
  and ask whether p(GM-move) systematically beats / loses to / matches the
  uniform-random baseline log(1/n_legal).

Physics notes:
  - 1/r is the 3-D Coulomb potential; on a 2-D domain the natural Green's
    function of the Laplacian is -log(r). 1/r is kept per spec; if you ever
    want to switch, change one line in `_kernel`.
  - ε regularises the piece singularities. Dirichlet energy of 1/r in 2-D
    diverges in the continuum; on the discrete grid it is finite but
    depends on (grid_resolution, ε). Compare positions/games with one
    fixed FieldConfig.

Dependencies: python-chess, numpy.
"""

from __future__ import annotations

import io
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import chess
import chess.pgn
import numpy as np


# ---------- Configuration ----------

DEFAULT_MASSES: Dict[int, float] = {
    chess.PAWN:    1.0,
    chess.KNIGHT:  3.0,
    chess.BISHOP:  3.0,
    chess.ROOK:    5.0,
    chess.QUEEN:   9.0,
    chess.KING:  100.0,
}


@dataclass
class FieldConfig:
    grid_resolution: int = 64
    epsilon: float = 0.1
    masses: Dict[int, float] = field(default_factory=lambda: dict(DEFAULT_MASSES))
    signed: bool = True   # +mass for White, -mass for Black


# ---------- Continuous field ----------

class InformationField:
    """Coulomb-like 2-D potential generated by chess pieces.

        Z(x, y) = Σ_i  s_i · m_i / (r_i + ε)

    r_i is Euclidean distance from grid point (x, y) to piece i,
    s_i ∈ {+1, -1} is the color sign (if `signed`), m_i is piece mass.
    """

    def __init__(self, cfg: FieldConfig):
        self.cfg = cfg
        n = cfg.grid_resolution
        self.x_axis = np.linspace(0.0, 8.0, n)
        self.y_axis = np.linspace(0.0, 8.0, n)
        self.dx = 8.0 / (n - 1)
        # indexing='xy' → X varies along axis 1 (cols), Y along axis 0 (rows)
        self.X, self.Y = np.meshgrid(self.x_axis, self.y_axis, indexing="xy")

    @staticmethod
    def _kernel(r: np.ndarray, eps: float) -> np.ndarray:
        # 3-D Coulomb form on a 2-D domain. Swap for `-np.log(r + eps)` for
        # the natural 2-D Green's function of the Laplacian.
        return 1.0 / (r + eps)

    def potential(self, board: chess.Board) -> np.ndarray:
        Z = np.zeros_like(self.X)
        eps = self.cfg.epsilon
        for sq in chess.SQUARES:
            piece = board.piece_at(sq)
            if piece is None:
                continue
            m = self.cfg.masses[piece.piece_type]
            if self.cfg.signed:
                s = +1.0 if piece.color == chess.WHITE else -1.0
            else:
                s = +1.0
            px = chess.square_file(sq) + 0.5
            py = chess.square_rank(sq) + 0.5
            r = np.sqrt((self.X - px) ** 2 + (self.Y - py) ** 2)
            Z += s * m * self._kernel(r, eps)
        return Z

    def gradient(self, Z: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        gy, gx = np.gradient(Z, self.dx, self.dx)
        return gx, gy

    def tension_field(self, Z: np.ndarray) -> np.ndarray:
        gx, gy = self.gradient(Z)
        return np.sqrt(gx * gx + gy * gy)

    def dirichlet_energy(self, Z: np.ndarray) -> float:
        """E = ∫ ‖∇Z‖² dA  — total field energy of the configuration."""
        gx, gy = self.gradient(Z)
        return float(np.sum(gx * gx + gy * gy) * self.dx * self.dx)


# ---------- Measurement records ----------

@dataclass
class PositionMetrics:
    fen: str
    ply: int
    side_to_move: str           # "white" | "black"
    field_energy: float         # Dirichlet energy of current position
    total_tension_L1: float     # ∫ ‖∇Z‖ dA  (L¹ norm of gradient)
    max_tension: float
    causal_entropy: float       # bits
    policy_max_prob: float
    n_legal_moves: int


@dataclass
class MoveAnalysis:
    uci: str
    energy_after: float
    delta_energy: float
    probability: float
    rank: int                   # 1 = highest probability


# ---------- Sensor ----------

class ActProofSensor:
    """Measurement instrument for ActProof field metrics on chess positions.

    Does NOT play. Returns scalar metrics + per-move stochastic-policy stats.

    Usage:
        sensor = ActProofSensor(beta=0.01)
        metrics, moves   = sensor.measure(board)
        trajectory       = sensor.analyze_game(pgn_text)
        beta_star, curve = sensor.fit_beta(pgn_text)
    """

    def __init__(self, cfg: Optional[FieldConfig] = None, beta: float = 0.01):
        self.cfg = cfg or FieldConfig()
        self.field = InformationField(self.cfg)
        # β: Boltzmann inverse temperature. Tune to observed energy scale.
        # Start at 0.01; energies are typically O(10²–10⁴) for grid_res=64.
        self.beta = beta

    # -- single-position measurement --

    def measure(self, board: chess.Board) -> Tuple[PositionMetrics, List[MoveAnalysis]]:
        Z = self.field.potential(board)
        T = self.field.tension_field(Z)
        E = self.field.dirichlet_energy(Z)

        moves = list(board.legal_moves)

        side = "white" if board.turn == chess.WHITE else "black"
        if not moves:
            return (
                PositionMetrics(
                    fen=board.fen(),
                    ply=board.ply(),
                    side_to_move=side,
                    field_energy=E,
                    total_tension_L1=float(np.sum(T) * self.field.dx ** 2),
                    max_tension=float(np.max(T)),
                    causal_entropy=0.0,
                    policy_max_prob=1.0,
                    n_legal_moves=0,
                ),
                [],
            )

        # Energies of resulting positions
        energies = np.empty(len(moves))
        for i, mv in enumerate(moves):
            board.push(mv)
            energies[i] = self.field.dirichlet_energy(self.field.potential(board))
            board.pop()

        probs = self._boltzmann(energies, self.beta)
        S = float(-np.sum(probs * np.log2(probs + 1e-12)))

        order = np.argsort(-probs)
        ranks = np.empty_like(order)
        ranks[order] = np.arange(1, len(order) + 1)

        move_records = [
            MoveAnalysis(
                uci=mv.uci(),
                energy_after=float(energies[i]),
                delta_energy=float(energies[i] - E),
                probability=float(probs[i]),
                rank=int(ranks[i]),
            )
            for i, mv in enumerate(moves)
        ]

        metrics = PositionMetrics(
            fen=board.fen(),
            ply=board.ply(),
            side_to_move=side,
            field_energy=float(E),
            total_tension_L1=float(np.sum(T) * self.field.dx ** 2),
            max_tension=float(np.max(T)),
            causal_entropy=S,
            policy_max_prob=float(probs.max()),
            n_legal_moves=len(moves),
        )
        return metrics, move_records

    @staticmethod
    def _boltzmann(energies: np.ndarray, beta: float) -> np.ndarray:
        logits = -beta * (energies - energies.min())
        w = np.exp(logits)
        return w / w.sum()

    # -- full-game measurement --

    def analyze_game(self, pgn_text: str) -> List[Dict]:
        game = chess.pgn.read_game(io.StringIO(pgn_text))
        if game is None:
            return []
        board = game.board()
        rows: List[Dict] = []
        for played in game.mainline_moves():
            metrics, move_anls = self.measure(board)
            played_uci = played.uci()
            row = next((m for m in move_anls if m.uci == played_uci), None)
            rows.append({
                "ply": metrics.ply,
                "side": metrics.side_to_move,
                "field_energy": metrics.field_energy,
                "max_tension": metrics.max_tension,
                "total_tension_L1": metrics.total_tension_L1,
                "causal_entropy": metrics.causal_entropy,
                "policy_max_prob": metrics.policy_max_prob,
                "n_legal_moves": metrics.n_legal_moves,
                "played_uci": played_uci,
                "played_probability": row.probability if row else None,
                "played_rank": row.rank if row else None,
                "played_delta_energy": row.delta_energy if row else None,
            })
            board.push(played)
        return rows

    # -- diagnostic: fit β to maximise log-likelihood of GM moves --

    def fit_beta(
        self,
        pgn_text: str,
        beta_grid: Optional[np.ndarray] = None,
    ) -> Tuple[float, np.ndarray]:
        """Search β ∈ grid for max mean log p(GM-move). Caches per-position
        energies once so the scan is cheap."""
        if beta_grid is None:
            beta_grid = np.logspace(-4, 1, 25)

        game = chess.pgn.read_game(io.StringIO(pgn_text))
        if game is None:
            return self.beta, np.zeros_like(beta_grid)
        board = game.board()

        per_pos_energies: List[Tuple[np.ndarray, int]] = []   # (energies, played_idx)
        for played in game.mainline_moves():
            moves = list(board.legal_moves)
            if not moves:
                board.push(played)
                continue
            energies = np.empty(len(moves))
            for i, mv in enumerate(moves):
                board.push(mv)
                energies[i] = self.field.dirichlet_energy(self.field.potential(board))
                board.pop()
            try:
                played_idx = moves.index(played)
            except ValueError:
                played_idx = -1
            if played_idx >= 0:
                per_pos_energies.append((energies, played_idx))
            board.push(played)

        if not per_pos_energies:
            return self.beta, np.zeros_like(beta_grid)

        ll_curve = np.empty_like(beta_grid)
        for k, b in enumerate(beta_grid):
            lls = []
            for energies, idx in per_pos_energies:
                probs = self._boltzmann(energies, b)
                lls.append(np.log(probs[idx] + 1e-12))
            ll_curve[k] = float(np.mean(lls))
        best = int(np.argmax(ll_curve))
        return float(beta_grid[best]), ll_curve


# ---------- Demo ----------

KASPAROV_TOPALOV_1999 = """
[Event "Hoogovens"]
[White "Kasparov, Garry"]
[Black "Topalov, Veselin"]
[Result "1-0"]

1. e4 d6 2. d4 Nf6 3. Nc3 g6 4. Be3 Bg7 5. Qd2 c6 6. f3 b5 7. Nge2 Nbd7
8. Bh6 Bxh6 9. Qxh6 Bb7 10. a3 e5 11. O-O-O Qe7 12. Kb1 a6 13. Nc1 O-O-O
14. Nb3 exd4 15. Rxd4 c5 16. Rd1 Nb6 17. g3 Kb8 18. Na5 Ba8 19. Bh3 d5
20. Qf4+ Ka7 21. Rhe1 d4 22. Nd5 Nbxd5 23. exd5 Qd6 24. Rxd4 cxd4
25. Re7+ Kb6 26. Qxd4+ Kxa5 27. b4+ Ka4 28. Qc3 Qxd5 29. Ra7 Bb7
30. Rxb7 Qc4 31. Qxf6 Kxa3 32. Qxa6+ Kxb4 33. c3+ Kxc3 34. Qa1+ Kd2
35. Qb2+ Kd1 36. Bf1 Rd2 37. Rd7 Rxd7 38. Bxc4 bxc4 39. Qxh8 Rd3
40. Qa8 c3 41. Qa4+ Ke1 42. f4 f5 43. Kc1 Rd2 44. Qa7 1-0
"""


def demo() -> None:
    sensor = ActProofSensor(beta=0.01)

    # 1) Starting position
    board = chess.Board()
    m, moves = sensor.measure(board)
    print("=== Starting position ===")
    print(f"  Field energy E (Dirichlet) : {m.field_energy:10.3f}")
    print(f"  Total tension ∫T dA (L¹)   : {m.total_tension_L1:10.3f}")
    print(f"  Max tension                : {m.max_tension:10.3f}")
    print(f"  Causal entropy S           : {m.causal_entropy:10.3f}  bits")
    print(f"  Policy max-prob            : {m.policy_max_prob:10.4f}")
    print(f"  Legal moves                : {m.n_legal_moves}")
    print("  Top 5 by stochastic policy:")
    for mv in sorted(moves, key=lambda x: -x.probability)[:5]:
        print(f"    {mv.uci:6s}  p={mv.probability:.4f}   ΔE={mv.delta_energy:+8.3f}")

    # 2) Game trajectory
    print("\n=== Kasparov–Topalov 1999, trajectory ===")
    traj = sensor.analyze_game(KASPAROV_TOPALOV_1999)
    print(f"  Plies analysed: {len(traj)}")

    probs   = np.array([r["played_probability"] for r in traj if r["played_probability"] is not None])
    ranks   = np.array([r["played_rank"]        for r in traj if r["played_rank"]        is not None])
    legal_n = np.array([r["n_legal_moves"]      for r in traj])

    if probs.size:
        logp_actual  = float(np.mean(np.log(probs + 1e-12)))
        logp_uniform = float(np.mean(-np.log(legal_n)))
        print(f"  Mean played-move probability   : {probs.mean():.4f}")
        print(f"  Median played-move probability : {np.median(probs):.4f}")
        print(f"  Mean rank of played move       : {ranks.mean():.2f}  (1 = top)")
        print(f"  Mean legal moves per position  : {legal_n.mean():.1f}")
        print(f"  Mean log p(GM-move)            : {logp_actual:+.3f}")
        print(f"  Mean log p(uniform random)     : {logp_uniform:+.3f}")
        print(f"  → Signal vs uniform Δlog-p     : {logp_actual - logp_uniform:+.3f}   "
              f"(>0 → sensor agrees with GM,  <0 → anti-correlates)")

    # 3) Fit β
    print("\n=== β-fit (max log-likelihood of GM moves) ===")
    beta_star, curve = sensor.fit_beta(KASPAROV_TOPALOV_1999)
    print(f"  β* = {beta_star:.5f}")
    print(f"  log-likelihood at β*       : {curve.max():+.3f}")
    print(f"  log-likelihood at β = 0    : {curve[0]:+.3f}    (≈ uniform)")
    # If β* ~ 0 → no useful signal in our energy.
    # If β* > 0 and ll(β*) > ll(0) → low-energy moves preferred by GM.
    # If β* < 0 (extend grid) → GM prefers high-energy moves.

    # 4) First 10 plies dump
    print("\n  First 10 plies:")
    print(f"  {'ply':>3}  {'side':6s} {'E':>8s} {'S':>6s} {'pmax':>6s} "
          f"{'move':6s} {'p(mv)':>8s} {'rank':>4s}")
    for r in traj[:10]:
        print(f"  {r['ply']:>3}  {r['side']:6s} "
              f"{r['field_energy']:8.1f} {r['causal_entropy']:6.2f} "
              f"{r['policy_max_prob']:6.3f} "
              f"{r['played_uci']:6s} {r['played_probability']:8.4f} {r['played_rank']:>4}")


if __name__ == "__main__":
    demo()
